#!/bin/bash

# Script para debug do Minishell - apenas comandos válidos
echo "pwd"
echo "echo \"=== Minishell Debug Test ===\""
echo "export TESTVAR=funcionando"
echo "echo \"Variável exportada: \$TESTVAR\""
echo "ls -la | head -5"
echo "date"
echo "echo \"teste output\" > debug.txt"
echo "cat debug.txt"
echo "echo \"append test\" >> debug.txt"
echo "cat < debug.txt"
echo "ls -la | head -8 | tail -3"
echo "cat << END"
echo "Esta é uma linha de heredoc"
echo "Variável expandida: \$TESTVAR"
echo "Teste completo!"
echo "END"
echo "false"
echo "echo \"Exit status após false: \$?\""
echo "true"
echo "echo \"Exit status após true: \$?\""
echo "rm -f debug.txt"
echo "echo \"=== Debug completo! Tudo funcionando! ===\""
echo "exit" 